<?php

namespace ContainerEy2Bcej;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHautelookAlice_Console_Command_Doctrine_DoctrineOrmLoadDataFixturesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hautelook_alice.console.command.doctrine.doctrine_orm_load_data_fixtures_command' shared service.
     *
     * @return \Hautelook\AliceBundle\Console\Command\Doctrine\DoctrineOrmLoadDataFixturesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hautelook'.\DIRECTORY_SEPARATOR.'alice-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Doctrine'.\DIRECTORY_SEPARATOR.'DoctrineOrmLoadDataFixturesCommand.php';

        $container->services['hautelook_alice.console.command.doctrine.doctrine_orm_load_data_fixtures_command'] = $instance = new \Hautelook\AliceBundle\Console\Command\Doctrine\DoctrineOrmLoadDataFixturesCommand('hautelook:fixtures:load', ($container->services['doctrine'] ?? $container->load('getDoctrineService')), ($container->services['hautelook_alice.loader'] ?? $container->load('getHautelookAlice_LoaderService')));

        $instance->setName('hautelook:fixtures:load');
        $instance->setDescription('Load data fixtures to your database.');

        return $instance;
    }
}
