<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEy2Bcej\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEy2Bcej/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEy2Bcej.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEy2Bcej\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEy2Bcej\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ey2Bcej',
    'container.build_id' => '7cfe5c11',
    'container.build_time' => 1732614478,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEy2Bcej');
